# GitHub Actions Workflow
# Build with Visual C++ on Windows
# Copyright 2019-2021 kaoru  https://www.tetengo.org/

name: Windows - Visual C++

on:
  push:
    branches: [ master ]
    tags:     [ v* ]
  pull_request:
    branches: [ master ]

env:
  CACHE_REV:        0
  TETENGO_VER:      1.3.2
  CONCURRENT_BUILD: 4
  BOOST_VER:        1_75_0
  BOOST_VER_DOT:    1.75.0

jobs:
  build:
    name:    Build
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Cache Boost build
      uses: actions/cache@v1
      with:
        path: ..\boost_build
        key: ${{ env.CACHE_REV }}-Windows-VisualCpp-Boost-${{ env.BOOST_VER }}
    
    - name: Build Boost
      shell: cmd
      run: |
        mkdir ..\boost_build
        cd ..\boost_build
        rem curl -L -o boost_%BOOST_VER%.tar.gz https://downloads.sourceforge.net/project/boost/boost/%BOOST_VER_DOT%/boost_%BOOST_VER%.tar.gz
        curl -L -o boost_%BOOST_VER%.tar.gz https://dl.bintray.com/boostorg/release/%BOOST_VER_DOT%/source/boost_%BOOST_VER%.tar.gz
        tar -xf boost_%BOOST_VER%.tar.gz
        cd boost_%BOOST_VER%
        call bootstrap.bat
        b2.exe -j ${{ env.CONCURRENT_BUILD }} toolset=msvc-14.2 address-model=32 variant=release link=static --stagedir="stage\Win32" stage
        b2.exe -j ${{ env.CONCURRENT_BUILD }} toolset=msvc-14.2 address-model=64 variant=release link=static --stagedir="stage\x64"   stage
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Build 32bit
      shell: cmd
      run: |
        set BOOST_INCLUDE=%GITHUB_WORKSPACE%\..\boost_build\boost_%BOOST_VER%
        set BOOST_LIB_x86=%GITHUB_WORKSPACE%\..\boost_build\boost_%BOOST_VER%\stage\Win32\lib
        msbuild /t:Rebuild /m:1 /p:Configuration=Release;Platform=x86 tetengo.sln
    
    - name: Build 64bit
      shell: cmd
      run: |
        set BOOST_INCLUDE=%GITHUB_WORKSPACE%\..\boost_build\boost_%BOOST_VER%
        set BOOST_LIB_x64=%GITHUB_WORKSPACE%\..\boost_build\boost_%BOOST_VER%\stage\x64\lib
        msbuild /t:Rebuild /m:1 /p:Configuration=Release;Platform=x64 tetengo.sln
    
    - name: Install
      shell: cmd
      run: |
        tool\install_tetengo_library.bat bin\tetengo-windows-%TETENGO_VER%
    
    - name: Make archive
      shell: powershell
      run: |
        Compress-Archive -Path .\bin\tetengo-windows-$env:TETENGO_VER -DestinationPath .\bin\tetengo-windows-$env:TETENGO_VER.zip
    
    - name: Move artifacts
      shell: cmd
      run: |
        mkdir artifacts
        move bin\tetengo-windows-%TETENGO_VER%.zip artifacts
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts-windows
        path: artifacts
